const ORIGINS=new Set((process.env.ALLOWED_ORIGINS||"https://sron2527.github.io").split(",").map(s=>s.trim()).filter(Boolean));
function cors(req,res){const o=req.headers.origin;if(o&&ORIGINS.has(o)){res.setHeader("Access-Control-Allow-Origin",o);res.setHeader("Vary","Origin")}res.setHeader("Access-Control-Allow-Methods","POST,OPTIONS");res.setHeader("Access-Control-Allow-Headers","Content-Type")}
function clean(v,max=500){return String(v??"").replace(/[\u0000-\u001F\u007F]/g," ").replace(/\s+/g," ").trim().slice(0,max)}
function dataPart(dataUrl){const m=String(dataUrl||"").match(/^data:(image\/(?:jpeg|jpg|png|webp));base64,([A-Za-z0-9+/=]+)$/i);if(!m)return null;const bytes=Math.floor(m[2].length*3/4);if(bytes>1700000)throw new Error("IMAGE_TOO_LARGE");return {inline_data:{mime_type:m[1].replace("image/jpg","image/jpeg"),data:m[2]}}}
async function callGemini(parts,opt={}){const key=process.env.GEMINI_API_KEY||process.env.GOOGLE_API_KEY;if(!key)throw new Error("GEMINI_NOT_CONFIGURED");const model=process.env.GEMINI_MODEL||"gemini-3.8-flash";const body={contents:[{parts}],generationConfig:{temperature:.2}};if(opt.json)body.generationConfig.responseMimeType="application/json";if(opt.search)body.tools=[{google_search:{}}];const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),22000);try{const r=await fetch("https://generativelanguage.googleapis.com/v1beta/models/"+encodeURIComponent(model)+":generateContent",{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":key},body:JSON.stringify(body),signal:ctrl.signal});if(!r.ok){const t=await r.text();throw new Error("Gemini "+r.status+" "+t.slice(0,300))}return await r.json()}finally{clearTimeout(timer)}}
function textOf(d){return (d?.candidates?.[0]?.content?.parts||[]).map(p=>p.text||"").join("\n").trim()}
function parseJson(text){let t=String(text||"").trim().replace(/^```json/i,"").replace(/^```/,"").replace(/```$/,"").trim();const a=t.indexOf("{"),b=t.lastIndexOf("}");if(a>=0&&b>a)t=t.slice(a,b+1);return JSON.parse(t)}
function sourcesOf(d){const gm=d?.candidates?.[0]?.groundingMetadata||d?.candidates?.[0]?.grounding_metadata||{};const chunks=gm.groundingChunks||gm.grounding_chunks||[];const out=[],seen=new Set();for(const c of chunks){const w=c.web||c?.chunk?.web;const url=w?.uri||w?.url;if(!url||seen.has(url))continue;seen.add(url);let domain="";try{domain=new URL(url).hostname.replace(/^www\./,"")}catch{}out.push({title:clean(w?.title||domain||"แหล่งข้อมูล",180),url,domain})}return out.slice(0,8)}
export default async function handler(req,res){
 cors(req,res);if(req.method==="OPTIONS")return res.status(204).end();if(req.method!=="POST")return res.status(405).json({error:"Method not allowed"});res.setHeader("Cache-Control","no-store");
 try{
  if(!(process.env.GEMINI_API_KEY||process.env.GOOGLE_API_KEY))return res.status(503).json({error:"ระบบ AI ยังไม่ได้ตั้งค่า Gemini API ใน Vercel"});
  const mode=req.body?.mode==="antique"?"antique":"amulet";const front=dataPart(req.body?.front);const back=dataPart(req.body?.back);if(!front)return res.status(400).json({error:"กรุณาส่งรูปด้านหน้าก่อน"});
  const note=clean(req.body?.note,500);const subject=mode==="amulet"?"พระเครื่องไทย":"ของเก่า ของโบราณ หรือของสะสม";
  const prompt=["คุณเป็นผู้ช่วยค้นข้อมูลจากภาพสำหรับเว็บเช็คของไทย AI","วัตถุในภาพคือโหมด: "+subject,"งานของคุณคือช่วยระบุเบื้องต้นจากลักษณะที่มองเห็นเท่านั้น ห้ามยืนยันว่าแท้หรือปลอม และห้ามอ้างว่ารับรองมูลค่า","ถ้าภาพไม่ชัดหรือข้อมูลไม่พอ ให้บอกตรงๆ ว่าไม่แน่ใจ","ข้อมูลเพิ่มเติมจากผู้ใช้: "+(note||"ไม่มี"),"คืน JSON เท่านั้นตามโครงสร้างนี้:","{ \"name\":\"ชื่อที่คาดว่าใกล้เคียงที่สุด หรือ ยังระบุไม่ได้ชัดเจน\", \"type\":\"ประเภท/รุ่น/พิมพ์ ถ้าระบุได้\", \"origin\":\"วัด ผู้สร้าง แบรนด์ ประเทศ หรือแหล่งที่มา ถ้าระบุได้\", \"era\":\"ช่วงปีหรือยุคโดยประมาณ\", \"material\":\"วัสดุ/เนื้อที่มองเห็นหรือคาดว่าเป็น\", \"confidence\":0, \"summary\":\"สรุปภาษาไทยสั้นๆ\", \"features\":[\"จุดสังเกตจากภาพ 1\",\"จุดสังเกตจากภาพ 2\"], \"searchQuery\":\"ข้อความสั้นๆ ที่เหมาะสำหรับค้นเว็บเพื่อหาราคาและข้อมูลอ้างอิง\" }","confidence คือความมั่นใจในการระบุว่าเป็นอะไรเท่านั้น ไม่ใช่ความมั่นใจว่าแท้"].join("\n");
  const parts=[{text:prompt},front];if(back)parts.push(back);const vision=await callGemini(parts,{json:true});let info;try{info=parseJson(textOf(vision))}catch{throw new Error("AI_PARSE_IDENTIFY")}
  info.confidence=Math.max(0,Math.min(100,Number(info.confidence)||0));info.name=clean(info.name,180)||"ยังระบุไม่ได้ชัดเจน";info.type=clean(info.type,180);info.origin=clean(info.origin,180);info.era=clean(info.era,120);info.material=clean(info.material,120);info.summary=clean(info.summary,400);info.features=Array.isArray(info.features)?info.features.map(x=>clean(x,180)).filter(Boolean).slice(0,8):[];
  const q=clean(info.searchQuery||[info.name,info.type,info.origin].filter(Boolean).join(" "),260);let market={priceRange:"ยังประเมินไม่ได้",priceNote:"ยังไม่พบข้อมูลตลาดที่น่าเชื่อถือเพียงพอจากการค้นครั้งนี้"},sources=[];
  if(q&&info.confidence>=25){const marketPrompt=["ค้นเว็บเกี่ยวกับ \""+q+"\" สำหรับตลาดไทย","ต้องการข้อมูลอ้างอิงเพื่อช่วยผู้ใช้ประเมินช่วงราคาของ "+subject+" ที่ระบุเบื้องต้นว่า \""+info.name+"\"","ระวังเรื่องความแท้ สภาพ ความนิยม รุ่นย่อย และราคาตั้งขายที่อาจไม่ใช่ราคาซื้อขายจริง","ห้ามแต่งราคาหากหาแหล่งรองรับไม่ได้","ตอบเป็น JSON เท่านั้น: { \"priceRange\":\"ช่วงราคาเป็นเงินบาท เช่น 1,500–3,000 บาท หรือ ยังประเมินไม่ได้\", \"priceNote\":\"อธิบายสั้นๆ ว่าช่วงราคานี้อ้างจากอะไรและมีข้อจำกัดอะไร\" }"].join("\n");try{const grounded=await callGemini([{text:marketPrompt}],{search:true});sources=sourcesOf(grounded);const raw=textOf(grounded);try{const m=parseJson(raw);market.priceRange=clean(m.priceRange,120)||market.priceRange;market.priceNote=clean(m.priceNote,500)||market.priceNote}catch{market.priceNote=clean(raw,500)||market.priceNote}}catch(e){market.priceNote="ระบุวัตถุได้เบื้องต้น แต่การค้นราคาตลาดไม่สำเร็จในรอบนี้ ควรตรวจสอบจากแหล่งซื้อขายหลายแห่ง"}}
  return res.status(200).json({ok:true,privacyMode:"stateless",name:info.name,type:info.type,origin:info.origin,era:info.era,material:info.material,confidence:info.confidence,summary:info.summary,features:info.features,priceRange:market.priceRange,priceNote:market.priceNote,sources});
 }catch(e){const msg=String(e?.message||e);if(msg.includes("GEMINI_NOT_CONFIGURED"))return res.status(503).json({error:"ระบบ AI ยังไม่ได้ตั้งค่า Gemini API ใน Vercel"});if(msg.includes("IMAGE_TOO_LARGE"))return res.status(413).json({error:"รูปมีขนาดใหญ่เกินไป กรุณาถ่ายหรือเลือกใหม่"});console.error("checkthai",msg);return res.status(502).json({error:"วิเคราะห์ไม่สำเร็จในขณะนี้ กรุณาลองใหม่ด้วยภาพที่ชัดขึ้น"})}
}